# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: fytinnovations.userconnect::lang.category.label

# Model Form Field configuration
form: $/SitiosAgenciaDigital\Subscribe/models/category/fields.yaml

# Model Class name
modelClass: SitiosAgenciaDigital\Subscribe\Models\Category

# Default redirect location
defaultRedirect: SitiosAgenciaDigital\Subscribe/categories

# Create page
create:
    title: fytinnovations.userconnect::lang.category.create_title
    redirect: SitiosAgenciaDigital\Subscribe/categories/update/:id
    redirectClose: SitiosAgenciaDigital\Subscribe/categories

# Update page
update:
    title: fytinnovations.userconnect::lang.category.update_title
    redirect: SitiosAgenciaDigital\Subscribe/categories
    redirectClose: SitiosAgenciaDigital\Subscribe/categories

# Preview page
preview:
    title: fytinnovations.userconnect::lang.category.preview_title