# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: sitiosagenciadigital.subscribe::lang.category.label

# Model Form Field configuration
form: $/sitiosagenciadigital/subscribe/models/category/fields.yaml

# Model Class name
modelClass: SitiosAgenciaDigital\Subscribe\Models\Category

# Default redirect location
defaultRedirect: sitiosagenciadigital/subscribe/categories

# Create page
create:
    title: sitiosagenciadigital.subscribe::lang.category.create_title
    redirect: sitiosagenciadigital/subscribe/categories/update/:id
    redirectClose: sitiosagenciadigital/subscribe/categories

# Update page
update:
    title: sitiosagenciadigital.subscribe::lang.category.update_title
    redirect: sitiosagenciadigital/subscribe/categories
    redirectClose: sitiosagenciadigital/subscribe/categories

# Preview page
preview:
    title: sitiosagenciadigital.subscribe::lang.category.preview_title