# ===================================
#  Import/Export Behavior Config
# ===================================
export:
    title: fytinnovations.userconnect::lang.subscribers.export

    modelClass: Fytinnovations\UserConnect\Models\SubscriberExport
    list: $/fytinnovations/userconnect/models/subscriber/columns.yaml
