# ===================================
#  Import/Export Behavior Config
# ===================================
export:
    title: fytinnovations.userconnect::lang.subscriptions.export

    modelClass: Fytinnovations\UserConnect\Models\SubscriptionExport
    list: $/fytinnovations/userconnect/models/subscription/columns.yaml
