# ===================================
#  List Behavior Config
# ===================================

title: sitiosagenciadigital.subscribe::lang.subscription.list_title
list: ~/plugins/sitiosagenciadigital/subscribe/models/subscription/columns.yaml
modelClass: sitiosagenciadigital\subscribe\Models\Subscription
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 10
showCheckboxes: true
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: Search..
export:
    useList: true
