# ===================================
#  Import/Export Behavior Config
# ===================================
export:
    title: sitiosagenciadigital.subscribe::lang.subscriptions.export

    modelClass: SitiosAgenciaDigital\Subscribe\Models\SubscriptionExport
    list: $/SitiosAgenciaDigital\Subscribe/models/subscription/columns.yaml
