# ===================================
#  List Behavior Config
# ===================================

title: sitiosagenciadigital.subscribe::lang.subscribers.list_title
list: ~/plugins/sitiosagenciadigital/subscribe/models/subscriber/columns.yaml
modelClass: sitiosagenciadigital\subscribe\Models\Subscriber
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 10
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: Search..
export:
    useList: true
