# ===================================
#  List Behavior Config
# ===================================

title: fytinnovations.userconnect::lang.subscribers.list_title
list: ~/plugins/SitiosAgenciaDigital\Subscribe/models/subscriber/columns.yaml
modelClass: SitiosAgenciaDigital\Subscribe\Models\Subscriber
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 10
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: Search..
export:
    useList: true
